baseurl = "/"
title = "WORLDWIDE GLOBAL"
languageCode = "en-us"
theme = "light"


enableRobotsTXT = true
googleAnalytics = "UA-79785814-1"


 [params]
   description = "acceleration and world peace "
   author = ""
   powered_by = false
