baseurl = "/"
title = "WORLDWIDE GLOBAL"
languageCode = "en-us"
theme = "light"


enableRobotsTXT = true
googleAnalytics = ""


 [params]
   description = "acceleration and world peace"
   author = ""
   powered_by = false
