baseurl = "/"
title = "WORLDWIDE GLOBAL"
languageCode = "en-us"
theme = "light"
paginate = 7

enableRobotsTXT = true
googleAnalytics = ""



 [params]
   description = "acceleration and world peace"
   author = ""
   powered_by = false
   logo = "img/wwg-logo.png"
   show_menu = true

   [menu]
  [[menu.main]]
    name = "img/wwg-logo.png"
    weight = 1
    identifier = "home"
    url = "/"

